# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: python/tdg/docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: python/tdg
  system_packages: true
